CREATE TABLE IF NOT EXISTS `PREFIX_gamifications_rank` (
  `id_gamifications_rank` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_group` INT(11) UNSIGNED NOT NULL,
  `id_shop` INT(11) UNSIGNED NOT NULL,
  `must_spend_points` INT(11) UNSIGNED NOT NULL,
  `must_spend_money` DECIMAL(17, 2) UNSIGNED NOT NULL,
  `date_add` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_upd` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_gamifications_rank`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;